### ISSUE TITLE
Missing source file and GL error.

### ISSUE THREAD

**Issue by LiuXinqi12** [xuxy09/RSC-Net#1]
It seems that some source files are still missing. Would you please update it? Thanks. 
Also, it seems that there is a problem with pyrender, and I get an error when running the program.

Traceback (most recent call last):
  File "demo.py", line 54, in <module>
    img_renderer = Renderer(focal_length=constants.FOCAL_LENGTH, img_res=constants.IMG_RES, faces=smpl_neutral.faces)
  File "/home/RSC-Net/utils/renderer.py", line 17, in __init__
    point_size=1.0)
  File "/home/anaconda3/envs/rsc-net/lib/python3.7/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/anaconda3/envs/rsc-net/lib/python3.7/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/home/anaconda3/envs/rsc-net/lib/python3.7/site-packages/pyrender/platforms/pyglet_platform.py", line 52, in init_context
    width=1, height=1)
  File "/home/anaconda3/envs/rsc-net/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 173, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/anaconda3/envs/rsc-net/lib/python3.7/site-packages/pyglet/window/__init__.py", line 606, in __init__
    context = config.create_context(gl.current_context)
  File "/home/anaconda3/envs/rsc-net/lib/python3.7/site-packages/pyglet/gl/xlib.py", line 204, in create_context
    return XlibContextARB(self, share)
  File "/home/anaconda3/envs/rsc-net/lib/python3.7/site-packages/pyglet/gl/xlib.py", line 314, in __init__
    super(XlibContext13, self).__init__(config, share)
  File "/home/anaconda3/envs/rsc-net/lib/python3.7/site-packages/pyglet/gl/xlib.py", line 218, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context

**Comment by xuxy09** [comment]
Seems an OpenGL error. Can you try a reinstallation with the instructions here: https://pyrender.readthedocs.io/en/latest/install/index.html#installing-osmesa?

**Comment by LiuXinqi12** [comment]
Frustratingly, I tried to use OSMesa to reinstallation , but other errors appeared, which seem to be related to pyrender and have not been resolved. https://github.com/mmatl/pyrender/issues/81

when using _os.environ['PYOPENGL_PLATFORM'] = 'osmesa'_
```
Traceback (most recent call last):
  File "demo.py", line 54, in <module>
    img_renderer = Renderer(focal_length=constants.FOCAL_LENGTH, img_res=constants.IMG_RES, faces=smpl_neutral.faces)
  File "/home/disk/study/RSC-Net/utils/renderer.py", line 17, in __init__
    self.renderer = pyrender.OffscreenRenderer(viewport_width=224,viewport_height=224, point_size=1.0)
  File "/home/anaconda3/envs/rsc-net/lib/python3.7/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/anaconda3/envs/rsc-net/lib/python3.7/site-packages/pyrender/offscreen.py", line 150, in _create
    self._platform.make_current()
  File "/home/anaconda3/envs/rsc-net/lib/python3.7/site-packages/pyrender/platforms/osmesa.py", line 44, in make_current
    self.viewport_width, self.viewport_height
AssertionError

```

when using _os.environ['PYOPENGL_PLATFORM'] = 'egl'_
```
Traceback (most recent call last):
  File "demo.py", line 54, in <module>
    img_renderer = Renderer(focal_length=constants.FOCAL_LENGTH, img_res=constants.IMG_RES, faces=smpl_neutral.faces)
  File "/home/RSC-Net/utils/renderer.py", line 17, in __init__
    self.renderer = pyrender.OffscreenRenderer(viewport_width=224,viewport_height=224, point_size=1.0)
  File "/home/anaconda3/envs/rsc-net/lib/python3.7/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/anaconda3/envs/rsc-net/lib/python3.7/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/home/anaconda3/envs/rsc-net/lib/python3.7/site-packages/pyrender/platforms/egl.py", line 188, in init_context
    EGL_NO_CONTEXT, context_attributes
  File "/home/anaconda3/envs/rsc-net/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 409, in __call__
    return self( *args, **named )
  File "/home/anaconda3/envs/rsc-net/lib/python3.7/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 12297,
	baseOperation = eglCreateContext,
	cArguments = (
		<OpenGL._opaque.EGLDisplay_pointer object at 0x7f15b00b1200>,
		<OpenGL._opaque.EGLConfig_pointer object at 0x7f15b00ca8c0>,
		<OpenGL._opaque.EGLContext_pointer object at 0x7f15b03379e0>,
		<OpenGL.arrays.lists.c_int_Array_7 object at 0x7f15b03604d0>,
	),
	result = <OpenGL._opaque.EGLContext_pointer object at 0x7f15b00b19e0>
)
```

**Comment by xuxy09** [comment]
Hi, I just write a new "demo_nr.py" which does not rely on Pyrender. You can use it in the same way as "demo.py". Let me know if this works for you.

**Comment by LiuXinqi12** [comment]
It's working now, thank you very much!

**Comment by MengHao666** [comment]
> Hi, I just write a new "demo_nr.py" which does not rely on Pyrender. You can use it in the same way as "demo.py". Let me know if this works for you.

Hi, does nerual_render only support render mesh in image of square size?

**Comment by MengHao666** [comment]
> It's working now, thank you very much!

Hi, do u use neural_render in headless server? Have u succeeded in using pyrender  in headless server?

**Comment by xuxy09** [comment]
> > Hi, I just write a new "demo_nr.py" which does not rely on Pyrender. You can use it in the same way as "demo.py". Let me know if this works for you.
> 
> Hi, does nerual_render only support render mesh in image of square size?

You can check this with the author of neural render.

**Comment by xuxy09** [comment]
> > It's working now, thank you very much!
> 
> Hi, do u use neural_render in headless server? Have u succeeded in using pyrender in headless server?

Yes, I can run pyrender on my server with OSMesa.

**Comment by MengHao666** [comment]
> > > It's working now, thank you very much!
> > 
> > 
> > Hi, do u use neural_render in headless server? Have u succeeded in using pyrender in headless server?
> 
> Yes, I can run pyrender on my server with OSMesa.

I met some problems and really hope u can help me.Can u give me your email address?In this way, we can have further talk.

**Comment by krips89** [comment]
How did you solve this problem? Just saying that it works now does not help others.

**Comment by YunjieYu** [comment]
> > > It's working now, thank you very much!
> > 
> > 
> > Hi, do u use neural_render in headless server? Have u succeeded in using pyrender in headless server?
> 
> Yes, I can run pyrender on my server with OSMesa.

Hi, could you provide some suggestions on how to run pyrender on headless server with OSMesa? Thanks in advance!
