### ISSUE TITLE
bug in eval.py

### ISSUE THREAD

**Issue by Arnav-Purushotam** [xuxy09/RSC-Net#9]
there seems to be a bug in eval.py
it no longer works

error:

Traceback (most recent call last):
  File "eval.py", line 196, in <module>
    run_evaluation(hmr_model, ds, eval_size=args.eval_size, batch_size=args.batch_size, num_workers=args.num_workers)
  File "eval.py", line 143, in run_evaluation
    global_orient=pred_rotmat[:, 0].unsqueeze(1), pose2rot=False)
  File "C:\Users\Asus\anaconda3\envs\RSC-net\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\dev\projects\football AR\RSC-Net-master\RSC-Net-master\models\smpl.py", line 23, in forward
    smpl_output = super(SMPL, self).forward(*args, **kwargs)
  File "C:\Users\Asus\anaconda3\envs\RSC-net\lib\site-packages\smplx\body_models.py", line 376, in forward
    self.lbs_weights, pose2rot=pose2rot, dtype=self.dtype)
  File "C:\Users\Asus\anaconda3\envs\RSC-net\lib\site-packages\smplx\lbs.py", line 205, in lbs
    J_transformed, A = batch_rigid_transform(rot_mats, J, parents, dtype=dtype)
  File "C:\Users\Asus\anaconda3\envs\RSC-net\lib\site-packages\smplx\lbs.py", line 347, in batch_rigid_transform
    rel_joints.view(-1, 3, 1)).view(-1, joints.shape[1], 4, 4)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

**Comment by xuxy09** [comment]
Hi, it seems your error is due to an external package: smpl. I guess you have the wrong version.

**Comment by BivinCBenny** [comment]
@Arnav-Purushotam Were you able to fix this issue?
